name: jacksi_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  get: ^4.6.5
  flutter_svg: ^2.0.4
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  flutter_vector_icons: ^2.0.0
  shimmer: ^3.0.0
  equatable: ^2.0.5
  image_picker: ^1.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/
      - assets/animations/
      - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Arabic Bold 700.otf
        - asset: assets/fonts/Montserrat-Arabic Light 300.otf
        - asset: assets/fonts/Montserrat-Arabic Medium 500.otf
        - asset: assets/fonts/Montserrat-Arabic Regular 400.otf
  
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
